export let data = [
  {
    Id: 10001,
    Name: "Muhammet Enes Şahin",
    Mail: "es@enessahin.dev",
    Designation: "Frontend Developer",
    Location: "Türkiye",
    Status: "Active",
    Trustworthiness: "Perfect",
    Proficiency: "95",
    Address: "Demetgul Mah. 417.Sk 4/31",
    Verified: !0,
  },
  {
    Id: 10002,
    Name: "Jane Smith",
    Mail: "jane.smith@example.com",
    Designation: "UI/UX Designer",
    Location: "San Francisco",
    Status: "Inactive",
    Trustworthiness: "Sufficient",
    Proficiency: "50",
    Address: "1029 - 12th Ave. S.",
    Verified: !0,
  },
  {
    Id: 10003,
    Name: "Fuller Buchanan",
    Mail: "fuller10@harpy.com",
    Designation: "Manager",
    Location: "Canada",
    Status: "Inactive",
    Trustworthiness: "Insufficient",
    Proficiency: "30",
    Address: "Via Ludovico il Moro 22",
    Verified: !0,
  },
  {
    Id: 10004,
    Name: "Vincent Zachery",
    Mail: "vincentzachery.23@mail.com",
    Designation: "Project Lead",
    Location: "USA",
    Status: "Inactive",
    Trustworthiness: "Insufficient",
    Proficiency: "40",
    Address: "Santiago, C67",
    Verified: !0,
  },
  {
    Id: 10005,
    Name: "Smith Johnson",
    Mail: "smith.johnson@example.com",
    Designation: "Software Engineer",
    Location: "USA",
    Status: "Active",
    Trustworthiness: "Perfect",
    Proficiency: "80",
    Address: "Los Angeles, A167",
    Verified: !0,
  },
  {
    Id: 10006,
    Name: "Wolfgang Doncaster",
    Mail: "wolfdoncaster@example.com",
    Designation: "Game Developer",
    Location: "Germany",
    Status: "Active",
    Trustworthiness: "Sufficient",
    Proficiency: "75",
    Address: "Berlin, Kreuzberg B33",
    Verified: !0,
  },
  {
    Id: 10007,
    Name: "John Smith",
    Mail: "john.smith@example.com",
    Designation: "Software Engineer",
    Location: "Australia",
    Status: "Active",
    Trustworthiness: "Sufficient",
    Proficiency: "75",
    Address: "Rua do Paço, 167",
    Verified: !0,
  },
  {
    Id: 10008,
    Name: "Belinda Miçotelakis",
    Mail: "bell.micotelakis@example.com",
    Designation: "Backend Developer",
    Location: "Greece",
    Status: "Inactive",
    Trustworthiness: "Insufficient",
    Address: "2nd District of Peristeri, 20C",
    Proficiency: "25",
    Verified: !0,
  },
  {
    Id: 10009,
    Name: "Gregor Bleatzky",
    Mail: "gregor.bleatzky@example.com",
    Designation: "UI/UX Designer",
    Location: "Ukraine",
    Status: "Active",
    Trustworthiness: "Sufficient",
    Address: "36, Parnykova Street",
    Proficiency: "75",
    Verified: !0,
  },
  {
    Id: 10010,
    Name: "Igor Pertina",
    Mail: "igor.pertina@example.com",
    Designation: "Frontend Engineer",
    Location: "Moldova",
    Status: "Active",
    Trustworthiness: "Perfect",
    Address: "64, Strada Aeroport",
    Proficiency: "95",
    Verified: !0,
  },
  {
    Id: 10012,
    Name: "Hakan Yılmaz",
    Mail: "hakan.yilmaz@example.com",
    Designation: "Q/A Test Engineer",
    Location: "Türkiye",
    Status: "Active",
    Trustworthiness: "Perfect",
    Address: "Ata Cd. 24/A, Balçova, İzmir",
    Proficiency: "85",
    Verified: !0,
  },
];
